src = ["src"]
extend-select = ["B", "E", "F", "I", "N", "UP", "W"]
ignore = [
    "B009",
    "B015",
    "B018",
    "B027",
    "B028",
    "B904",
    "N818",
    "UP032",
    "UP030",
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
]
# according to the documentation, should not be needed with:
#       requires-python = ">=3.7"
target-version = "py37"
