name: Linting

on:
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - ".pre-commit-config.yaml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/lint.yml"
      - ".pre-commit-config.yaml"
      - "**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  FORCE_COLOR: 1

jobs:
  lint:
    name: nox -s lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        name: Install Python
        with:
          python-version: "3.10"
          cache: "pip"

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        name: Setup uv

      - name: Run `nox -s lint`
        run: pipx run nox -s lint -- --show-diff-on-failure

  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    # Linting verifies that the project is in an acceptable state to create files
    # for releasing.
    # And this action should be run whenever a release is ready to go public as
    # the version number will be changed by editing __init__.py.
    needs: lint

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        name: Setup uv

      - name: Build
        run: uv build

      - name: Build
        run: uvx twine check --strict ./dist/*

      - name: Archive files
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: dist
          path: dist
