name: Check package metadata

on: [push]

jobs:
  packaging:
    name: tox -e packaging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade tox

    - name: Run checks
      run: python -m tox -e packaging
