name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ref:
        # require SHA as tags and branches are mutable
        description: Full git commit SHA (not branch/tag)
        required: true
        type: string

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}

    steps:
      - name: Log inputs
        run: echo "${INPUTS}"
        env:
          INPUTS: ${{ toJSON(inputs)  }}

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
          fetch-depth: 0

      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        name: Setup uv

      - name: Check ref is the commit SHA
        # require SHA as tags and branches are mutable
        run: test "${INPUTS_REF}"
          = "$(git log --max-count=1 --format=format:%h)"
          || test "${INPUTS_REF}"
          = "$(git log --max-count=1 --format=format:%H)"
        env:
          INPUTS_REF: ${{ inputs.ref }}

      - name: Get git tag
        id: get-tag
        run: echo "tag=$(git tag --points-at "$INPUTS_REF")" >> "$GITHUB_OUTPUT"
        env:
          INPUTS_REF: ${{ inputs.ref }}

      - name: Install nox with pbs
        run: pipx install nox[pbs]

      - name: Provision nox environment
        run: nox --install-only -s release_build

      - name: Build distribution via nox
        run: nox --no-install -R -s release_build

      - name: Upload distribution
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
        with:
          name: packages
          path: dist/
          if-no-files-found: error
          compression-level: 0

  publish:
    name: Publish
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/project/packaging/${{ needs.build.outputs.tag }}
    permissions:
      id-token: write # Allow OIDC id-token for authenticated publishing to PyPI
    # Only publish if there's a matching tag, and if this is not a fork
    if: needs.build.outputs.tag != '' && !github.event.repository.fork

    runs-on: ubuntu-latest

    steps:
      - name: Download distribution
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # 8.0.1
        with:
          name: packages
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
        with:
          print-hash: true
